// <auto-generated />
using System;
using DigitalBanking.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalBanking.DAL.Migrations
{
    [DbContext(typeof(DigitalBankingDbContext))]
    [Migration("20260913065639_TestMigration")]
    partial class TestMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalBanking.DAL.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DigitalBanking.DAL.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IncomeDetails")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DigitalBanking.DAL.Entities.LoanApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssessmentCompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExistingLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SchemeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LoanApplications");
                });

            modelBuilder.Entity("DigitalBanking.DAL.Entities.LoanProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoanProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            ProductCode = "PL",
                            ProductName = "Personal Loan"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            ProductCode = "HL",
                            ProductName = "Home Loan"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            ProductCode = "VL",
                            ProductName = "Vehicle Loan"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            ProductCode = "BL",
                            ProductName = "Business Loan"
                        });
                });

            modelBuilder.Entity("DigitalBanking.DAL.Entities.LoanScheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoanProductId")
                        .HasColumnType("int");

                    b.Property<string>("SchemeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoanProductId");

                    b.ToTable("LoanSchemes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestRate = 10.50m,
                            IsActive = true,
                            LoanProductId = 1,
                            SchemeCode = "PL-SAL",
                            SchemeName = "Salaried Personal Loan"
                        },
                        new
                        {
                            Id = 2,
                            InterestRate = 11.00m,
                            IsActive = true,
                            LoanProductId = 1,
                            SchemeCode = "PL-SELF",
                            SchemeName = "Self Employed Personal Loan"
                        },
                        new
                        {
                            Id = 3,
                            InterestRate = 10.25m,
                            IsActive = true,
                            LoanProductId = 1,
                            SchemeCode = "PL-MED",
                            SchemeName = "Medical Personal Loan"
                        },
                        new
                        {
                            Id = 4,
                            InterestRate = 11.50m,
                            IsActive = true,
                            LoanProductId = 1,
                            SchemeCode = "PL-TRV",
                            SchemeName = "Travel Personal Loan"
                        },
                        new
                        {
                            Id = 5,
                            InterestRate = 8.50m,
                            IsActive = true,
                            LoanProductId = 2,
                            SchemeCode = "HL-PUR",
                            SchemeName = "Home Purchase Loan"
                        },
                        new
                        {
                            Id = 6,
                            InterestRate = 8.25m,
                            IsActive = true,
                            LoanProductId = 2,
                            SchemeCode = "HL-CON",
                            SchemeName = "Home Construction Loan"
                        },
                        new
                        {
                            Id = 7,
                            InterestRate = 8.75m,
                            IsActive = true,
                            LoanProductId = 2,
                            SchemeCode = "HL-REN",
                            SchemeName = "Home Renovation Loan"
                        },
                        new
                        {
                            Id = 8,
                            InterestRate = 8.00m,
                            IsActive = true,
                            LoanProductId = 2,
                            SchemeCode = "HL-BT",
                            SchemeName = "Home Balance Transfer"
                        },
                        new
                        {
                            Id = 9,
                            InterestRate = 9.00m,
                            IsActive = true,
                            LoanProductId = 3,
                            SchemeCode = "VL-NCAR",
                            SchemeName = "New Car Loan"
                        },
                        new
                        {
                            Id = 10,
                            InterestRate = 10.50m,
                            IsActive = true,
                            LoanProductId = 3,
                            SchemeCode = "VL-UCAR",
                            SchemeName = "Used Car Loan"
                        },
                        new
                        {
                            Id = 11,
                            InterestRate = 10.25m,
                            IsActive = true,
                            LoanProductId = 3,
                            SchemeCode = "VL-BIKE",
                            SchemeName = "Two Wheeler Loan"
                        },
                        new
                        {
                            Id = 12,
                            InterestRate = 8.90m,
                            IsActive = true,
                            LoanProductId = 3,
                            SchemeCode = "VL-EV",
                            SchemeName = "Electric Vehicle Loan"
                        },
                        new
                        {
                            Id = 13,
                            InterestRate = 12.00m,
                            IsActive = true,
                            LoanProductId = 4,
                            SchemeCode = "BL-WC",
                            SchemeName = "Working Capital Loan"
                        },
                        new
                        {
                            Id = 14,
                            InterestRate = 11.50m,
                            IsActive = true,
                            LoanProductId = 4,
                            SchemeCode = "BL-MSME",
                            SchemeName = "MSME Business Loan"
                        },
                        new
                        {
                            Id = 15,
                            InterestRate = 12.25m,
                            IsActive = true,
                            LoanProductId = 4,
                            SchemeCode = "BL-EQP",
                            SchemeName = "Equipment Finance Loan"
                        },
                        new
                        {
                            Id = 16,
                            InterestRate = 13.00m,
                            IsActive = true,
                            LoanProductId = 4,
                            SchemeCode = "BL-STR",
                            SchemeName = "Startup Business Loan"
                        });
                });

            modelBuilder.Entity("SubscriptionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BusinessOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionRequests");
                });

            modelBuilder.Entity("DigitalBanking.DAL.Entities.LoanScheme", b =>
                {
                    b.HasOne("DigitalBanking.DAL.Entities.LoanProduct", "LoanProduct")
                        .WithMany("LoanSchemes")
                        .HasForeignKey("LoanProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanProduct");
                });

            modelBuilder.Entity("DigitalBanking.DAL.Entities.LoanProduct", b =>
                {
                    b.Navigation("LoanSchemes");
                });
#pragma warning restore 612, 618
        }
    }
}
